"""Add PokerTable

Revision ID: 2825785f5498
Revises: 267e81ba11e2
Create Date: 2026-05-13 03:37:49.556155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2825785f5498'
down_revision: Union[str, Sequence[str], None] = '267e81ba11e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poker_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deck', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('community_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('players_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_turn_index', sa.Integer(), nullable=False),
    sa.Column('pot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_bet', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dealer_button_index', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('big_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_tables_id'), 'poker_tables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poker_tables_id'), table_name='poker_tables')
    op.drop_table('poker_tables')
    # ### end Alembic commands ###
