"""add_crash_models

Revision ID: 3a2c4e5b6d7f
Revises: 2825785f5498
Create Date: 2026-05-16 04:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2c4e5b6d7f'
down_revision: Union[str, None] = '2825785f5498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default='BETTING'),
    sa.Column('crash_point', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_game_sessions_id'), 'crash_game_sessions', ['id'], unique=False)
    
    op.create_table('crash_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashout_multiplier', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payout', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['crash_game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_bets_id'), 'crash_bets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crash_bets_id'), table_name='crash_bets')
    op.drop_table('crash_bets')
    op.drop_index(op.f('ix_crash_game_sessions_id'), table_name='crash_game_sessions')
    op.drop_table('crash_game_sessions')
    # ### end Alembic commands ###
